services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: booking_dev
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-playground.sql

volumes:
  pgdata:
